// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: InvoiceV2.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace InvoicingV2 {

  /// <summary>Holder for reflection information generated from InvoiceV2.proto</summary>
  public static partial class InvoiceV2Reflection {

    #region Descriptor
    /// <summary>File descriptor for InvoiceV2.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InvoiceV2Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9JbnZvaWNlVjIucHJvdG8SCUludm9pY2luZxofZ29vZ2xlL3Byb3RvYnVm",
            "L3RpbWVzdGFtcC5wcm90bxoRSW52b2ljZUxpbmUucHJvdG8ijAIKB0ludm9p",
            "Y2USFgoOaW52b2ljZV9udW1iZXIYASABKAkSFQoNY3VzdG9tZXJfbmFtZRgD",
            "IAEoCRIwCgxpbnZvaWNlX2RhdGUYBCABKAsyGi5nb29nbGUucHJvdG9idWYu",
            "VGltZXN0YW1wEhQKDHRvdGFsX2Ftb3VudBgFIAEoAhI2ChFwYXltZW50X2Nv",
            "bmRpdGlvbhgGIAEoDjIbLkludm9pY2luZy5QYXltZW50Q29uZGl0aW9uEiUK",
            "BUxpbmVzGAcgAygLMhYuSW52b2ljaW5nLkludm9pY2VMaW5lEhgKEGN1c3Rv",
            "bWVyX2FkZHJlc3MYCCABKAlKBAgCEANSC2N1c3RvbWVyX2lkIiwKEkZpbmRJ",
            "bnZvaWNlUmVxdWVzdBIWCg5pbnZvaWNlX251bWJlchgBIAEoCSI6ChNGaW5k",
            "SW52b2ljZVJlc3BvbnNlEiMKB2ludm9pY2UYASABKAsyEi5JbnZvaWNpbmcu",
            "SW52b2ljZSJ5ChlGaW5kSW52b2ljZXNCeURhdGVSZXF1ZXN0Ei4KCnN0YXJ0",
            "X2RhdGUYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEiwKCGVu",
            "ZF9kYXRlGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCJBChpG",
            "aW5kSW52b2ljZXNCeURhdGVSZXNwb25zZRIjCgdpbnZvaWNlGAEgASgLMhIu",
            "SW52b2ljaW5nLkludm9pY2UqTwoQUGF5bWVudENvbmRpdGlvbhIICgRDQVNI",
            "EAASEAoMRU5EX09GX01PTlRIEAESDgoKU0lYVFlfREFZUxACEg8KC05JTkVU",
            "WV9EQVlTEAMyyAEKEEludm9pY2luZ1NlcnZpY2USTgoLRmluZEludm9pY2US",
            "HS5JbnZvaWNpbmcuRmluZEludm9pY2VSZXF1ZXN0Gh4uSW52b2ljaW5nLkZp",
            "bmRJbnZvaWNlUmVzcG9uc2UiABJkChJGaW5kSW52b2ljZXNCeURhdGUSJC5J",
            "bnZvaWNpbmcuRmluZEludm9pY2VzQnlEYXRlUmVxdWVzdBokLkludm9pY2lu",
            "Zy5GaW5kSW52b2ljZXNCeURhdGVSZXF1ZXN0IgAwAUIOqgILSW52b2ljaW5n",
            "VjJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Invoicing.InvoiceLineReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::InvoicingV2.PaymentCondition), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::InvoicingV2.Invoice), global::InvoicingV2.Invoice.Parser, new[]{ "InvoiceNumber", "CustomerName", "InvoiceDate", "TotalAmount", "PaymentCondition", "Lines", "CustomerAddress" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InvoicingV2.FindInvoiceRequest), global::InvoicingV2.FindInvoiceRequest.Parser, new[]{ "InvoiceNumber" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InvoicingV2.FindInvoiceResponse), global::InvoicingV2.FindInvoiceResponse.Parser, new[]{ "Invoice" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InvoicingV2.FindInvoicesByDateRequest), global::InvoicingV2.FindInvoicesByDateRequest.Parser, new[]{ "StartDate", "EndDate" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::InvoicingV2.FindInvoicesByDateResponse), global::InvoicingV2.FindInvoicesByDateResponse.Parser, new[]{ "Invoice" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PaymentCondition {
    [pbr::OriginalName("CASH")] Cash = 0,
    [pbr::OriginalName("END_OF_MONTH")] EndOfMonth = 1,
    [pbr::OriginalName("SIXTY_DAYS")] SixtyDays = 2,
    [pbr::OriginalName("NINETY_DAYS")] NinetyDays = 3,
  }

  #endregion

  #region Messages
  public sealed partial class Invoice : pb::IMessage<Invoice> {
    private static readonly pb::MessageParser<Invoice> _parser = new pb::MessageParser<Invoice>(() => new Invoice());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Invoice> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InvoicingV2.InvoiceV2Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Invoice() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Invoice(Invoice other) : this() {
      invoiceNumber_ = other.invoiceNumber_;
      customerName_ = other.customerName_;
      invoiceDate_ = other.invoiceDate_ != null ? other.invoiceDate_.Clone() : null;
      totalAmount_ = other.totalAmount_;
      paymentCondition_ = other.paymentCondition_;
      lines_ = other.lines_.Clone();
      customerAddress_ = other.customerAddress_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Invoice Clone() {
      return new Invoice(this);
    }

    /// <summary>Field number for the "invoice_number" field.</summary>
    public const int InvoiceNumberFieldNumber = 1;
    private string invoiceNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string InvoiceNumber {
      get { return invoiceNumber_; }
      set {
        invoiceNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "customer_name" field.</summary>
    public const int CustomerNameFieldNumber = 3;
    private string customerName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CustomerName {
      get { return customerName_; }
      set {
        customerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "invoice_date" field.</summary>
    public const int InvoiceDateFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Timestamp invoiceDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp InvoiceDate {
      get { return invoiceDate_; }
      set {
        invoiceDate_ = value;
      }
    }

    /// <summary>Field number for the "total_amount" field.</summary>
    public const int TotalAmountFieldNumber = 5;
    private float totalAmount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float TotalAmount {
      get { return totalAmount_; }
      set {
        totalAmount_ = value;
      }
    }

    /// <summary>Field number for the "payment_condition" field.</summary>
    public const int PaymentConditionFieldNumber = 6;
    private global::InvoicingV2.PaymentCondition paymentCondition_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::InvoicingV2.PaymentCondition PaymentCondition {
      get { return paymentCondition_; }
      set {
        paymentCondition_ = value;
      }
    }

    /// <summary>Field number for the "Lines" field.</summary>
    public const int LinesFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Invoicing.InvoiceLine> _repeated_lines_codec
        = pb::FieldCodec.ForMessage(58, global::Invoicing.InvoiceLine.Parser);
    private readonly pbc::RepeatedField<global::Invoicing.InvoiceLine> lines_ = new pbc::RepeatedField<global::Invoicing.InvoiceLine>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Invoicing.InvoiceLine> Lines {
      get { return lines_; }
    }

    /// <summary>Field number for the "customer_address" field.</summary>
    public const int CustomerAddressFieldNumber = 8;
    private string customerAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CustomerAddress {
      get { return customerAddress_; }
      set {
        customerAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Invoice);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Invoice other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InvoiceNumber != other.InvoiceNumber) return false;
      if (CustomerName != other.CustomerName) return false;
      if (!object.Equals(InvoiceDate, other.InvoiceDate)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TotalAmount, other.TotalAmount)) return false;
      if (PaymentCondition != other.PaymentCondition) return false;
      if(!lines_.Equals(other.lines_)) return false;
      if (CustomerAddress != other.CustomerAddress) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (InvoiceNumber.Length != 0) hash ^= InvoiceNumber.GetHashCode();
      if (CustomerName.Length != 0) hash ^= CustomerName.GetHashCode();
      if (invoiceDate_ != null) hash ^= InvoiceDate.GetHashCode();
      if (TotalAmount != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TotalAmount);
      if (PaymentCondition != 0) hash ^= PaymentCondition.GetHashCode();
      hash ^= lines_.GetHashCode();
      if (CustomerAddress.Length != 0) hash ^= CustomerAddress.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (InvoiceNumber.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(InvoiceNumber);
      }
      if (CustomerName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CustomerName);
      }
      if (invoiceDate_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(InvoiceDate);
      }
      if (TotalAmount != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(TotalAmount);
      }
      if (PaymentCondition != 0) {
        output.WriteRawTag(48);
        output.WriteEnum((int) PaymentCondition);
      }
      lines_.WriteTo(output, _repeated_lines_codec);
      if (CustomerAddress.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(CustomerAddress);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (InvoiceNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InvoiceNumber);
      }
      if (CustomerName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CustomerName);
      }
      if (invoiceDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InvoiceDate);
      }
      if (TotalAmount != 0F) {
        size += 1 + 4;
      }
      if (PaymentCondition != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PaymentCondition);
      }
      size += lines_.CalculateSize(_repeated_lines_codec);
      if (CustomerAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CustomerAddress);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Invoice other) {
      if (other == null) {
        return;
      }
      if (other.InvoiceNumber.Length != 0) {
        InvoiceNumber = other.InvoiceNumber;
      }
      if (other.CustomerName.Length != 0) {
        CustomerName = other.CustomerName;
      }
      if (other.invoiceDate_ != null) {
        if (invoiceDate_ == null) {
          InvoiceDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        InvoiceDate.MergeFrom(other.InvoiceDate);
      }
      if (other.TotalAmount != 0F) {
        TotalAmount = other.TotalAmount;
      }
      if (other.PaymentCondition != 0) {
        PaymentCondition = other.PaymentCondition;
      }
      lines_.Add(other.lines_);
      if (other.CustomerAddress.Length != 0) {
        CustomerAddress = other.CustomerAddress;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            InvoiceNumber = input.ReadString();
            break;
          }
          case 26: {
            CustomerName = input.ReadString();
            break;
          }
          case 34: {
            if (invoiceDate_ == null) {
              InvoiceDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(InvoiceDate);
            break;
          }
          case 45: {
            TotalAmount = input.ReadFloat();
            break;
          }
          case 48: {
            PaymentCondition = (global::InvoicingV2.PaymentCondition) input.ReadEnum();
            break;
          }
          case 58: {
            lines_.AddEntriesFrom(input, _repeated_lines_codec);
            break;
          }
          case 66: {
            CustomerAddress = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class FindInvoiceRequest : pb::IMessage<FindInvoiceRequest> {
    private static readonly pb::MessageParser<FindInvoiceRequest> _parser = new pb::MessageParser<FindInvoiceRequest>(() => new FindInvoiceRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FindInvoiceRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InvoicingV2.InvoiceV2Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FindInvoiceRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FindInvoiceRequest(FindInvoiceRequest other) : this() {
      invoiceNumber_ = other.invoiceNumber_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FindInvoiceRequest Clone() {
      return new FindInvoiceRequest(this);
    }

    /// <summary>Field number for the "invoice_number" field.</summary>
    public const int InvoiceNumberFieldNumber = 1;
    private string invoiceNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string InvoiceNumber {
      get { return invoiceNumber_; }
      set {
        invoiceNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FindInvoiceRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FindInvoiceRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InvoiceNumber != other.InvoiceNumber) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (InvoiceNumber.Length != 0) hash ^= InvoiceNumber.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (InvoiceNumber.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(InvoiceNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (InvoiceNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InvoiceNumber);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FindInvoiceRequest other) {
      if (other == null) {
        return;
      }
      if (other.InvoiceNumber.Length != 0) {
        InvoiceNumber = other.InvoiceNumber;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            InvoiceNumber = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class FindInvoiceResponse : pb::IMessage<FindInvoiceResponse> {
    private static readonly pb::MessageParser<FindInvoiceResponse> _parser = new pb::MessageParser<FindInvoiceResponse>(() => new FindInvoiceResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FindInvoiceResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InvoicingV2.InvoiceV2Reflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FindInvoiceResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FindInvoiceResponse(FindInvoiceResponse other) : this() {
      invoice_ = other.invoice_ != null ? other.invoice_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FindInvoiceResponse Clone() {
      return new FindInvoiceResponse(this);
    }

    /// <summary>Field number for the "invoice" field.</summary>
    public const int InvoiceFieldNumber = 1;
    private global::InvoicingV2.Invoice invoice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::InvoicingV2.Invoice Invoice {
      get { return invoice_; }
      set {
        invoice_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FindInvoiceResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FindInvoiceResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Invoice, other.Invoice)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (invoice_ != null) hash ^= Invoice.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (invoice_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Invoice);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (invoice_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Invoice);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FindInvoiceResponse other) {
      if (other == null) {
        return;
      }
      if (other.invoice_ != null) {
        if (invoice_ == null) {
          Invoice = new global::InvoicingV2.Invoice();
        }
        Invoice.MergeFrom(other.Invoice);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (invoice_ == null) {
              Invoice = new global::InvoicingV2.Invoice();
            }
            input.ReadMessage(Invoice);
            break;
          }
        }
      }
    }

  }

  public sealed partial class FindInvoicesByDateRequest : pb::IMessage<FindInvoicesByDateRequest> {
    private static readonly pb::MessageParser<FindInvoicesByDateRequest> _parser = new pb::MessageParser<FindInvoicesByDateRequest>(() => new FindInvoicesByDateRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FindInvoicesByDateRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InvoicingV2.InvoiceV2Reflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FindInvoicesByDateRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FindInvoicesByDateRequest(FindInvoicesByDateRequest other) : this() {
      startDate_ = other.startDate_ != null ? other.startDate_.Clone() : null;
      endDate_ = other.endDate_ != null ? other.endDate_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FindInvoicesByDateRequest Clone() {
      return new FindInvoicesByDateRequest(this);
    }

    /// <summary>Field number for the "start_date" field.</summary>
    public const int StartDateFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp startDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp StartDate {
      get { return startDate_; }
      set {
        startDate_ = value;
      }
    }

    /// <summary>Field number for the "end_date" field.</summary>
    public const int EndDateFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp endDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp EndDate {
      get { return endDate_; }
      set {
        endDate_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FindInvoicesByDateRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FindInvoicesByDateRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(StartDate, other.StartDate)) return false;
      if (!object.Equals(EndDate, other.EndDate)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (startDate_ != null) hash ^= StartDate.GetHashCode();
      if (endDate_ != null) hash ^= EndDate.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (startDate_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(StartDate);
      }
      if (endDate_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(EndDate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (startDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StartDate);
      }
      if (endDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EndDate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FindInvoicesByDateRequest other) {
      if (other == null) {
        return;
      }
      if (other.startDate_ != null) {
        if (startDate_ == null) {
          StartDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        StartDate.MergeFrom(other.StartDate);
      }
      if (other.endDate_ != null) {
        if (endDate_ == null) {
          EndDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        EndDate.MergeFrom(other.EndDate);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (startDate_ == null) {
              StartDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(StartDate);
            break;
          }
          case 18: {
            if (endDate_ == null) {
              EndDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(EndDate);
            break;
          }
        }
      }
    }

  }

  public sealed partial class FindInvoicesByDateResponse : pb::IMessage<FindInvoicesByDateResponse> {
    private static readonly pb::MessageParser<FindInvoicesByDateResponse> _parser = new pb::MessageParser<FindInvoicesByDateResponse>(() => new FindInvoicesByDateResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FindInvoicesByDateResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::InvoicingV2.InvoiceV2Reflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FindInvoicesByDateResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FindInvoicesByDateResponse(FindInvoicesByDateResponse other) : this() {
      invoice_ = other.invoice_ != null ? other.invoice_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FindInvoicesByDateResponse Clone() {
      return new FindInvoicesByDateResponse(this);
    }

    /// <summary>Field number for the "invoice" field.</summary>
    public const int InvoiceFieldNumber = 1;
    private global::InvoicingV2.Invoice invoice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::InvoicingV2.Invoice Invoice {
      get { return invoice_; }
      set {
        invoice_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FindInvoicesByDateResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FindInvoicesByDateResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Invoice, other.Invoice)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (invoice_ != null) hash ^= Invoice.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (invoice_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Invoice);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (invoice_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Invoice);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FindInvoicesByDateResponse other) {
      if (other == null) {
        return;
      }
      if (other.invoice_ != null) {
        if (invoice_ == null) {
          Invoice = new global::InvoicingV2.Invoice();
        }
        Invoice.MergeFrom(other.Invoice);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (invoice_ == null) {
              Invoice = new global::InvoicingV2.Invoice();
            }
            input.ReadMessage(Invoice);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
