/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var InvoiceLine_pb = require('./InvoiceLine_pb.js');
goog.object.extend(proto, InvoiceLine_pb);
goog.exportSymbol('proto.Invoicing.Invoice', null, global);
goog.exportSymbol('proto.Invoicing.PaymentCondition', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Invoicing.Invoice = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Invoicing.Invoice.repeatedFields_, null);
};
goog.inherits(proto.Invoicing.Invoice, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Invoicing.Invoice.displayName = 'proto.Invoicing.Invoice';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Invoicing.Invoice.repeatedFields_ = [7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Invoicing.Invoice.prototype.toObject = function(opt_includeInstance) {
  return proto.Invoicing.Invoice.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Invoicing.Invoice} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Invoicing.Invoice.toObject = function(includeInstance, msg) {
  var obj = {
    invoiceNumber: jspb.Message.getFieldWithDefault(msg, 1, ""),
    customerId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    customerName: jspb.Message.getFieldWithDefault(msg, 3, ""),
    invoiceDate: (f = msg.getInvoiceDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    totalAmount: +jspb.Message.getFieldWithDefault(msg, 5, 0.0),
    paymentCondition: jspb.Message.getFieldWithDefault(msg, 6, 0),
    linesList: jspb.Message.toObjectList(msg.getLinesList(),
    InvoiceLine_pb.InvoiceLine.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Invoicing.Invoice}
 */
proto.Invoicing.Invoice.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Invoicing.Invoice;
  return proto.Invoicing.Invoice.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Invoicing.Invoice} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Invoicing.Invoice}
 */
proto.Invoicing.Invoice.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setInvoiceNumber(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCustomerId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCustomerName(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setInvoiceDate(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setTotalAmount(value);
      break;
    case 6:
      var value = /** @type {!proto.Invoicing.PaymentCondition} */ (reader.readEnum());
      msg.setPaymentCondition(value);
      break;
    case 7:
      var value = new InvoiceLine_pb.InvoiceLine;
      reader.readMessage(value,InvoiceLine_pb.InvoiceLine.deserializeBinaryFromReader);
      msg.addLines(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Invoicing.Invoice.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Invoicing.Invoice.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Invoicing.Invoice} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Invoicing.Invoice.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInvoiceNumber();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCustomerId();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getCustomerName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getInvoiceDate();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getTotalAmount();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getPaymentCondition();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getLinesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      InvoiceLine_pb.InvoiceLine.serializeBinaryToWriter
    );
  }
};


/**
 * optional string invoice_number = 1;
 * @return {string}
 */
proto.Invoicing.Invoice.prototype.getInvoiceNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.Invoicing.Invoice.prototype.setInvoiceNumber = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 customer_id = 2;
 * @return {number}
 */
proto.Invoicing.Invoice.prototype.getCustomerId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.Invoicing.Invoice.prototype.setCustomerId = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string customer_name = 3;
 * @return {string}
 */
proto.Invoicing.Invoice.prototype.getCustomerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.Invoicing.Invoice.prototype.setCustomerName = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp invoice_date = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.Invoicing.Invoice.prototype.getInvoiceDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.Invoicing.Invoice.prototype.setInvoiceDate = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.Invoicing.Invoice.prototype.clearInvoiceDate = function() {
  this.setInvoiceDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Invoicing.Invoice.prototype.hasInvoiceDate = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional float total_amount = 5;
 * @return {number}
 */
proto.Invoicing.Invoice.prototype.getTotalAmount = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 5, 0.0));
};


/** @param {number} value */
proto.Invoicing.Invoice.prototype.setTotalAmount = function(value) {
  jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional PaymentCondition payment_condition = 6;
 * @return {!proto.Invoicing.PaymentCondition}
 */
proto.Invoicing.Invoice.prototype.getPaymentCondition = function() {
  return /** @type {!proto.Invoicing.PaymentCondition} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {!proto.Invoicing.PaymentCondition} value */
proto.Invoicing.Invoice.prototype.setPaymentCondition = function(value) {
  jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * repeated InvoiceLine Lines = 7;
 * @return {!Array<!proto.Invoicing.InvoiceLine>}
 */
proto.Invoicing.Invoice.prototype.getLinesList = function() {
  return /** @type{!Array<!proto.Invoicing.InvoiceLine>} */ (
    jspb.Message.getRepeatedWrapperField(this, InvoiceLine_pb.InvoiceLine, 7));
};


/** @param {!Array<!proto.Invoicing.InvoiceLine>} value */
proto.Invoicing.Invoice.prototype.setLinesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.Invoicing.InvoiceLine=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Invoicing.InvoiceLine}
 */
proto.Invoicing.Invoice.prototype.addLines = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.Invoicing.InvoiceLine, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.Invoicing.Invoice.prototype.clearLinesList = function() {
  this.setLinesList([]);
};


/**
 * @enum {number}
 */
proto.Invoicing.PaymentCondition = {
  CASH: 0,
  END_OF_MONTH: 1,
  SIXTY_DAYS: 2,
  NINETY_DAYS: 3
};

goog.object.extend(exports, proto.Invoicing);
